# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1raKyQOwesuaP2ErzB4adGJquLM6WJd6X
"""

'''
source : https://github.com/chen0040/keras-text-summarization
'''

from __future__ import print_function

import pandas as pd
from keras_text_summarization.library.seq2seq import Seq2SeqSummarizer
import numpy as np

np.random.seed(42)
data_dir_path = '.\demo\data' # refers to the demo/data folder
model_dir_path = '.\demo\models' # refers to the demo/models folder

print('loading csv file ...')
df = pd.read_csv(data_dir_path + "\fake_or_real_news.csv")
X = df['text']
Y = df.title

config = np.load(Seq2SeqSummarizer.get_config_file_path(model_dir_path=model_dir_path)).item()

summarizer = Seq2SeqSummarizer(config)
summarizer.load_weights(weight_file_path=Seq2SeqSummarizer.get_weight_file_path(model_dir_path=model_dir_path))

print('Headline Generator ...')
actual_text = input('Enter article : ')
actual_headline = input('Enter expected headline : ')
headline = summarizer.summarize(actual_text)
print('\nGenerated Headline: ', headline)